### ISSUE TITLE
source code?

### ISSUE THREAD

**Issue by anaraven** [jsajuria/estadoedita#1]
hola. Quiero hacer algo similar en Turquía. ¿dónde está el código? ÷o basta con las listas de IP?

Es decir, ¿qué hago con las IP?

gracias

**Comment by rderania** [comment]
no habla, espaniol???

**Comment by anaraven** [comment]
si hablo. No soy español.

Just in case: I want to do something similar in Turkey. Where is the code? Or is it enough with the lists of IP? 

In other words, what do I do with the IP?

**Comment by jsajuria** [comment]
HI, sorry for the late response!

EstadoEdita uses the anon framework, you can find it here https://github.com/edsu/anon
